### ISSUE TITLE
Chrome doesn't recognise manifest

### ISSUE THREAD

**Issue by HughEvans01** [spite/virtual-webcam#6]
I tried both downloading and cloning the repo but when I got to chrome://extensions and Load unpacked I get the following:
`Failed to load extension
File
~\Desktop\virtual-webcam\js
Error
Manifest file is missing or unreadable
Could not load manifest.`
The manifest file is physically there but it appears chrome doesn't recognise it. Am I missing something here?
Thanks in advance

**Comment by spite** [comment]
you seem to be loading the js folder. the manifest is in the root folder, and that's the one that needs to be loaded from the "Load unpacked" option in about:extensions.

**Comment by HughEvans01** [comment]
My bad, thanks for the speedy reply
